export const CUISINE = {
    ON_CUISINE_REQUEST: 'ON_CUISINE_REQUEST',
    ON_CUISINE_SUCCESS: 'ON_CUISINE_REQUEST',
    ON_CUISINE_ERROR: 'ON_CUISINE_REQUEST'
}

export const RECIPIES = {
    GET_RECIPIES_REQUEST: 'GET_RECIPIES_REQUEST',
    GET_RECIPIES_SUCCESS: 'GET_RECIPIES_SUCCESS',
    GET_RECIPIES_ERROR: 'GET_RECIPIES_ERROR'
}